[profile.default]
src = "src"
out = "out"
libs = ["lib"]
skip_contract_size = ["lib/account-abstraction/contracts/core/EntryPoint.sol"]

remappings = [
    '@account-abstraction/contracts=lib/account-abstraction/contracts',
]

[profile.ci]
skip_contract_size = ["lib/account-abstraction/contracts/core/EntryPoint.sol"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
